# **Project Title : Student Marks Analyzer**

---




# **Problem Statement** :





## Develop a program which analyzes the marks of multiple students to assign grades and extract insights




---



# Logic :




### The following program uses Numpy and Python to analyze marks of multiple students based on the input given by the user.



> It accepts inputs from user to create a database of marks to analyze using input statements lists and numpy arrays

> It assigns a grade [A-F] based on the average marks obtain for each student using for loop and conditional statements

> It also calculates the highest and lowest marks in the given data set using Mathematical Operations






# Code :

In [26]:
import numpy as np
master_student_marks_array = []

print("Enter marks of student for 5 subjects separated by spaces and no commas. Type 'exit' to finish.")

while True:
    user_input = input("Enter marks for 5 subjects max of 100 marks for each subject: ").strip()

    # To Check if the user wants to stop
    if user_input.lower() == 'exit':
        break

    # 2. Convert the input string into an array of integers
    # int(x) converts the strings to numbers
    sub_array = [int(x) for x in user_input.split()]

    # 3. Store the sub-array inside the master student marks array
    master_student_marks_array.append(sub_array)


print("\nFinal Master Array:")
print(master_student_marks_array)

#Total marks, Average marks, Highest and lowest marks calculations

def total_marks():
  total_student_marks = np.sum(master_student_marks_array,axis = 1)
  print(f"\n The total marks of the students are: \n{total_student_marks}")
total_marks()


average_student_marks = np.mean(master_student_marks_array,axis = 1)
print(f"\n The average marks of the students are: \n{average_student_marks}")

def highest_marks():
  highest_student_marks = np.max(master_student_marks_array,axis = 1)
  print(f"\n The highest marks of the students are: \n{highest_student_marks}")
highest_marks()

def lowest_marks():
  lowest_student_marks = np.min(master_student_marks_array,axis = 1)
  print(f"\n The lowest marks of the students are: \n{lowest_student_marks}")
lowest_marks()

# Grade Assigning:

print("\nNow we will assign grades to the students")
def grade_assigning():
  for i in average_student_marks:
    if i >= 90:
      print("Grade: A The student has passed!!!")
    elif i >= 75:
      print("Grade: B The student has passed!!")
    elif i >= 50:
      print("Grade: C The student has passed!")
    elif i >= 30:
      print("Grade: D The student has passed")
    else:
      print("Grade: F The student has failed :C ")
grade_assigning()

#Sample Output Below

Enter marks of student for 5 subjects separated by spaces and no commas. Type 'exit' to finish.
Enter marks for 5 subjects max of 100 marks for each subject: 0 0 0 0 0 
Enter marks for 5 subjects max of 100 marks for each subject: 90 90 90 90 90
Enter marks for 5 subjects max of 100 marks for each subject: 20 30 40 50 60 
Enter marks for 5 subjects max of 100 marks for each subject: exit 

Final Master Array:
[[0, 0, 0, 0, 0], [90, 90, 90, 90, 90], [20, 30, 40, 50, 60]]

 The total marks of the students are: 
[  0 450 200]

 The average marks of the students are: 
[ 0. 90. 40.]

 The highest marks of the students are: 
[ 0 90 60]

 The lowest marks of the students are: 
[ 0 90 20]

Now we will assign grades to the students
Grade: F The student has failed :C 
Grade: A The student has passed!!!
Grade: D The student has passed
